[package]
name = "bevy_status_bars_2d"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"

[dependencies.copyless]
version = "0.1.5"